title: Chuanzhi L
description: Talk is cheap. Show me the code

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: ChuanzhiL
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: lichuanzhi7909@gmail.com

google_analytics: "UA-58263416-1"
